version: '2'
services:
  activator:
    image: ingensi/play-framework
    volumes:
     - ./modigen-v3:/app
     - ./sbt:/root/.sbt
     - ./cache:/root/.ivy2/cache
    ports:
     - 9000:9000
    stdin_open: true
    network_mode: "host"

  db:
    image: mongo
    volumes:
     - ./mongo/:/data/db
    ports:
     - 27017:27017
