version: '2'
services:
  activator:
    image: ingensi/play-framework
    volumes:
     - ./modigen-v3:/app
     - ./sbt:/root/.sbt
     - ./cache:/root/.ivy2/cache
    ports:
     - localhost:9000:9000
    stdin_open: true
    links:
     - db
    command: ["activator", "-Dmongodb.ip=db", "run"]

  db:
    image: mongo
    volumes:
     - ./mongo:/data/db
    ports:
     - localhost:27017:27017
